services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_PASSWORD=postgres
    ports: ["5432:5432"]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped

  ingestion:
    build:
      context: .
      dockerfile: services/ingestion/Dockerfile
    depends_on: [redis]
    environment:
      - REDIS_ADDR=redis:6379
    ports: ["50051:50051"]
    restart: unless-stopped

  aggregator:
    build:
      context: .
      dockerfile: services/aggregator/Dockerfile
    depends_on: [redis]
    environment:
      - REDIS_ADDR=redis:6379
    ports: ["50053:50053"]
    restart: unless-stopped

  alerter:
    build:
      context: .
      dockerfile: services/alerter/Dockerfile
    depends_on: [aggregator]
    environment:
      - THRESHOLD_TEMP=28.0
      - THRESHOLD_HUM=70.0
    ports: ["50054:50054"]
    restart: unless-stopped

  queryapi:
    build:
      context: .
      dockerfile: services/query-api/Dockerfile
    depends_on: [timescaledb]
    ports: ["50052:50052"]
    restart: unless-stopped
