# docker-compose.yml  (2-space indentation)
services:
  api:
    build:
      context: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      APP_URL: http://app:8001
    depends_on:
      - app

  app:
    build:
      context: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    environment:
      DATA_URL: http://data:8002
      REDIS_HOST: redis
    depends_on:
      - data
      - redis

  data:
    build:
      context: ./data
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ds
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7
    # no host port needed

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ds
    # no host port needed
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ds"]
      interval: 2s
      timeout: 5s
      retries: 30
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
